name: Build OpenJDK 17 and 21 for iOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_iosport:
    strategy:
      matrix:
        version: [17, 21]
      fail-fast: false

    name: "Build Java ${{ matrix.version }} for iOS"
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          export PATH=/opt/procursus/bin:/opt/homebrew/bin:$PATH
          export JAVA_HOME=$(/usr/libexec/java_home -v ${{ matrix.version }})
          export BUILD_IOS=1
          export TARGET_VERSION=${{ matrix.version }}
          bash "1_ci_build_arch_aarch64.sh"

      - name: Upload raw JRE build
        uses: actions/upload-artifact@v4
        with:
          name: "jre${{ matrix.version }}-ios-aarch64"
          path: jre${{ matrix.version }}*.tar.xz

      - name: Upload debuginfo
        uses: actions/upload-artifact@v4
        with:
          name: "jre${{ matrix.version }}-ios-debuginfo-aarch64"
          path: dizout

  repack_ios_jre:
    needs: build_iosport
    runs-on: self-hosted
    strategy:
      matrix:
        version: [17, 21]
      fail-fast: false

    name: "Repack JRE ${{ matrix.version }} for Pojav"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built JRE
        uses: actions/download-artifact@v4
        with:
          name: "jre${{ matrix.version }}-ios-aarch64"
          path: pojav

      - name: Repack JRE for Pojav
        run: |
          export TARGET_VERSION=${{ matrix.version }}
          bash "9_repackjre.sh" $GITHUB_WORKSPACE/pojav $GITHUB_WORKSPACE/pojav/jre${{ matrix.version }}-pojav

      - name: Upload repacked JRE
        uses: actions/upload-artifact@v4
        with:
          name: "jre${{ matrix.version }}-pojav"
          path: pojav/jre${{ matrix.version }}-pojav/*
